- clients/restful-api/auth.md
> Upgrade auth page

- README.md
- SUMMARY.md
- clients/restful-api/k8stask.md
> Add k8s api page

- SUMMARY.md
Change-Id: Ic901c149cc5d29aa33f51040a467a201af0b4cef
> add schema api entrance in navigate bar

- clients/restful-api/traverser.md
add parameters of K-out API and K-neighbor API
> add parameters of K-out API and K-neighbor API

- clients/restful-api/gremlin.md
Change-Id: Ibb5d6f410f45b96c9a65033e7ac33e49426797e3
> fix gremlin job return code

- quickstart/hugegraph-loader.md
> Added doc about Hive

- clients/restful-api/graphs.md
- quickstart/hugegraph-tools.md
todo: update config description after complete graph-add
Change-Id: I3b61ed72dbca2f8bab6b65f0151f09203fa8a7fe
> add graph-add and graph-drop api and tools description

- quickstart/hugegraph-loader.md
add doc about input.dir_filter in mapping description file
> doc(loader): add doc about input.dir_filter

- clients/restful-api-v3/schema.md
Change-Id: I60506f025d778631184d8b37b0a691b2c93bc9c7
> add schema groovy get and update

- clients/restful-api-v3/graphspace.md
- clients/restful-api-v3/other.md
Change-Id: If49281ef3a33df40f1bcfd775c52d336123a45a3
> add graph space api description

- clients/hugegraph-api-v3.md
- clients/restful-api-v3/other.md
- clients/restful-api-v3/service.md
Change-Id: I55ad31855b0205adf5391454c409bdee82e42ad6
> add service api description

- clients/hugegraph-api-v3.md
- clients/restful-api-v3/other.md
- clients/restful-api-v3/schematemplate.md
Change-Id: I6c2163750ce93e099880401363bc0fb36e919913
> add schema template api description

- clients/restful-api-v3/graphs.md
Change-Id: Ie6d8d72e11aa84cf82adf816a17b4026a4800c9b
> add graph flush api description

- clients/restful-api-v3/edge.md
- clients/restful-api-v3/edgelabel.md
- clients/restful-api-v3/graphs.md
- clients/restful-api-v3/gremlin.md
- clients/restful-api-v3/indexlabel.md
- clients/restful-api-v3/k8stask.md
- clients/restful-api-v3/propertykey.md
- clients/restful-api-v3/rank.md
- clients/restful-api-v3/rebuild.md
- clients/restful-api-v3/task.md
- clients/restful-api-v3/traverser.md
- clients/restful-api-v3/variable.md
- clients/restful-api-v3/vertex.md
- clients/restful-api-v3/vertexlabel.md
Change-Id: I0156d3571b75e2f55e08b1aebae6d4ecd847399e
> update graph and schema api for graphspace added

- clients/restful-api-v3/service.md
Change-Id: I5defbcae7f78ea90222a73af5bbbb276e3cb7967
> improve service doc

- SUMMARY.md
- clients/restful-api-v3/schema.md
- clients/restful-api/schema.md
- quickstart/hugegraph-tools-v3.md
[三期] 新增Hugegraph tools v3版本文档
[三期] 完善获取全部schema的API参数示例
[二期] 完善获取全部schema的API参数详细信息
> 新增Hugegraph tools v3版本文档 & 完善schema的API参数文档

- quickstart/hugegraph-loader.md
Supports Kerberos authentication during Hive data import
> Hive data import

- clients/restful-api-v3/vertex.md
Change-Id: If1528759545f5b562624aa8b95fdfe8e302ee027
> fix vertex shard api

- clients/restful-api-v3/graphs.md
Change-Id: Iee5c53d78643fc535c8c7bc53229e6128ebd08fb
> add graph args

- clients/restful-api-v3/gremlin.md
Change-Id: If3f023f06c7abc42d32514c67804857e33a7bf98
> add gremlin unzip api

- clients/restful-api-v3/propertykey.md
Change-Id: I6bb3d373343c57e0242aa87c0ba391f3871551e5
> update name of  property key

- clients/restful-api-v3/propertykey.md
Change-Id: I43b24fbce15db4a796daca93d00231b7d9202d6d
> update pk name improve

- quickstart/hugegraph-loader-v3.md
Change-Id: I678f49d1a0eb106ab18c36112e2068c351b80502
> support extra_date_formats for file/hdfs

- clients/restful-api-v3/auth.md
Change-Id: I8329e5f537fff3a4e4ddf4d463a1b9aae012bd4a
> add kg-user-create and kg-login API description
